os: osx
language: generic
osx_image: xcode10.1
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - pip install six
  - brew update
  - brew install ruby
  - gem update --system
  - gem install travis --no-rdoc --no-ri
  #  - brew install --HEAD libimobiledevice
  - brew install ideviceinstaller
  - brew install ios-deploy
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
  - ./flutter/bin/flutter build -v ios
  # build/ios/iphoneos/Runner.app ができるので、fastlaneでビルド署名する
  - ./flutter/bin/flutter build -v apk
  # uild/app/outputs/apk/release/app-release.apk ができる

cache:
  directories:
    - $HOME/.pub-cache
