os: osx
language: android
osx_image: xcode10.1
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - android-26
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-24
  licenses:
    - android-sdk-license-.+
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - oracle-java8-installer
      - libstdc++6
      - fonts-droid
before_script:
  - pip install six
  - brew update
  - brew install ruby
  - gem update --system
  - gem install travis --no-rdoc --no-ri
  #  - brew install --HEAD libimobiledevice
  - brew install ideviceinstaller
  - brew install ios-deploy
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
  - ./flutter/bin/flutter build -v ios
  # build/ios/iphoneos/Runner.app ができるので、fastlaneでビルド署名する
  - ./flutter/bin/flutter build -v apk
  # uild/app/outputs/apk/release/app-release.apk ができる

cache:
  directories:
    - $HOME/.pub-cache
