os: osx
language: generic
osx_image: xcode9.4
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - pip install six
  - brew update
  - brew install --HEAD libimobiledevice
  - brew install ideviceinstaller
  - brew install ios-deploy
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1
  - ./flutter/bin/flutter doctor
script:
  - ./flutter/bin/flutter test
  - ./flutter/bin/flutter build -v ios

cache:
  directories:
    - $HOME/.pub-cache
